title: My test homepage
author: paulgreeneye
email: paulgreeneye@tuta.io
description: > # this means to ignore newlines until "baseurl:"
  That;s just tets site. I'm learning Jekyll and GitHub Pages.

# social links
twitter_username: paulgreeneye # DO NOT include the @ character, or else the build will fail!
github_username:  paulgreeneye # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
